# Generated by Django 4.2.11 on 2024-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order_tracking", "0002_alter_purchaseorder_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.TextField(),
        ),
    ]
